# Threshold defaults
DEFAULT_VISUAL_THRESHOLD: float = 0.7
DEFAULT_SCENE_THRESHOLD: float = 27.0
DEFAULT_VLM_GAPS_RADIUS: float = 30.0
DEFAULT_LLM_CONFIDENCE: float = 0.6
DEFAULT_VLM_CONFIDENCE: float = 0.55
DEFAULT_VLM_MIN_SHOT_DURATION: float = 0.4

# Text limits
MAX_REASON_LENGTH: int = 160
